---
abstract: 'Turns your script into a UNIX daemon process (the easy way).'
author:
  - 'Giacomo Montagner <gmork@entirelyunlike.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Script-Daemonizer
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Fcntl: 0
  File::Basename: 0
  File::Spec: 0
  File::Temp: 0
  POSIX: 0
  Test::More: 0
version: v0.91.00
